[project]
name = "codex-code-review-poc1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.21",
    "jinja2>=3.1.6",
    "paramiko>=4.0.0",
    "scp>=0.15.0",
]
